version: "3"

volumes:
  pgdata:

services:
  teste-postgres-compose:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    ports:
      - 12345:80
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
# Run container
# docker-compose -f postgres.yml --env-file .env  up -d
